#!/bin/sh

# Plugin to monitor the AWS CloudWatch metrics "EstimatedCharges"
# MIT License
# Mar 20, 2012
# version 0.0.1 Masahito Zembutsu (@zembutsu)

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title AWS EstimatedCharges (Total)'
        echo 'graph_args --base 1000 -l 0'
        echo "graph_category AWS";
        echo 'graph_vlabel USD'
        echo 'graph_scale no'
        echo 'graph_info EstimatedCharges (Total)'
        print_warning EstimatedCharges
        print_critical EstimatedCharges
        echo "EstimatedCharges.type GAUGE"
        echo 'EstimatedCharges.label EstimatedCharges'
        echo 'EstimatedCharges.info AWS EstimatedCharges (Total)'
        exit 0
fi

echo -n "EstimatedCharges.value "
cat /var/lib/munin/plugin-aws-cloudwatch/EstimatedCharges.dat | cut -f2 -d' '

